// Datos del menú - Azul Caribe Lounge
// tags: reservado para uso futuro (filtros eliminados del menú)
//
// IMPORTANTE sobre el tag "sinAlcohol":
// Este tag se usa SOLO para bebidas (café y bebidas sin alcohol) que no
// contienen alcohol. No se aplica a platos de comida — aunque un plato no
// lleve alcohol, no es una "bebida sin alcohol", así que no debe llevar
// este tag. Esto es a propósito para que el filtro "Sin Alcohol" muestre
// únicamente bebidas, nunca comida.
//
// IDIOMAS: "nombre" y "desc" son objetos {es, en, pt}. Para editar una
// traducción, cambia solo el texto dentro de las comillas de ese idioma.
// "badge" (opcional) es una clave que se traduce en i18n.js (BADGE_LABELS):
// "favorito" | "mustTry" | "chef" (platos de cocina) | "bartender" (cócteles/bar) | "nuevo".
const MENU_DATA = [
  // ---- DESAYUNO / MORNING / CAFÉ DA MANHÃ ----
  { id:"d1", cat:"desayuno",
    nombre:{ es:"Tortilla de Queso", en:"Cheese Omelet", pt:"Omelete de Queijo" },
    desc:{ es:"Esponjosa tortilla de queso servida con tocino, salchicha y papas.", en:"Fluffy cheese omelet served with bacon, sausage, and potatoes.", pt:"Omelete fofo de queijo servido com bacon, linguiça e batatas." },
    precio:24000, img:"desayuno-tortilla", tags:[] },
  { id:"d2", cat:"desayuno",
    nombre:{ es:"Arepas Grislet", en:"Griot Arepas", pt:"Arepas com Griot" },
    desc:{ es:"Arepas de maíz rellenas con griot haitiano y hogao.", en:"Corn arepas stuffed with Haitian griot and hogao sauce.", pt:"Arepas de milho recheadas com griot haitiano e molho hogao." },
    precio:28000, img:"desayuno-arepas-grislet", tags:[] },
  { id:"d3", cat:"desayuno",
    nombre:{ es:"Arepas con Hogao", en:"Arepas with Hogao", pt:"Arepas com Hogao" },
    desc:{ es:"Arepas servidas con salsa hogao tradicional.", en:"Arepas served with traditional hogao sauce.", pt:"Arepas servidas com molho hogao tradicional." },
    precio:28000, img:"desayuno-arepas-hogao", tags:[] },
  { id:"d4", cat:"desayuno",
    nombre:{ es:"Empanadas de Griot y Queso Costeño", en:"Griot & Costeño Cheese Empanadas", pt:"Empanadas de Griot e Queijo Costeño" },
    desc:{ es:"Empanadas rellenas de cerdo griot y queso costeño.", en:"Empanadas filled with griot pork and coastal cheese.", pt:"Empanadas recheadas com porco griot e queijo costeño." },
    precio:26000, img:"desayuno-empanadas", tags:[], badge:"favorito" },
  { id:"d5", cat:"desayuno",
    nombre:{ es:"Papa Criolla con Pikliz", en:"Criolla Potatoes with Pikliz", pt:"Batata Crioula com Pikliz" },
    desc:{ es:"Papas criollas doradas acompañadas de pikliz haitiano picante.", en:"Golden criolla potatoes served with spicy Haitian pikliz.", pt:"Batatas crioulas douradas acompanhadas de pikliz haitiano picante." },
    precio:22000, img:"desayuno-papa-criolla", tags:[] },
  { id:"d6", cat:"desayuno",
    nombre:{ es:"Adicional de Queso", en:"Extra Cheese", pt:"Adicional de Queijo" },
    desc:{ es:"Porción extra de queso para acompañar tu desayuno.", en:"Extra portion of cheese to add to your breakfast.", pt:"Porção extra de queijo para acompanhar seu café da manhã." },
    precio:5000, img:"aperitivo-papas-queso", tags:[] },
  { id:"d7", cat:"desayuno",
    nombre:{ es:"Desayuno Completo", en:"Full Breakfast", pt:"Café da Manhã Completo" },
    desc:{ es:"Huevos revueltos, chorizo, tocino y sándwich de jamón y queso a la plancha, acompañado de un bowl de fruta fresca.", en:"Scrambled eggs, sausage, bacon, and a grilled ham and cheese sandwich, served with a fresh fruit bowl.", pt:"Ovos mexidos, linguiça, bacon e sanduíche de presunto e queijo na chapa, acompanhado de um bowl de fruta fresca." },
    precio:25000, img:"desayuno-completo", tags:[] },

  // ---- APERITIVOS PARA COMPARTIR / STARTERS / APERITIVOS ----
  { id:"a1", cat:"aperitivos",
    nombre:{ es:"Patacones Fritos", en:"Fried Green Plantains", pt:"Patacones Fritos" },
    desc:{ es:"Plátanos verdes fritos crocantes.", en:"Crispy fried green plantains.", pt:"Bananas-da-terra verdes fritas e crocantes." },
    precio:24000, img:"aperitivo-patacones", tags:[] },
  { id:"a2", cat:"aperitivos",
    nombre:{ es:"Aborrajados Haitianos", en:"Haitian Aborrajados", pt:"Aborrajados Haitianos" },
    desc:{ es:"Frituras de plátano maduro rellenas.", en:"Stuffed sweet plantain fritters.", pt:"Frituras de banana-da-terra madura recheadas." },
    precio:24000, img:"aperitivo-aborrajados", tags:[] },
  { id:"a3", cat:"aperitivos",
    nombre:{ es:"Ceviche Mixto", en:"Mixed Ceviche", pt:"Ceviche Misto" },
    desc:{ es:"Pescado y mariscos marinados en jugo de limón.", en:"Fish and seafood cured in fresh lime juice.", pt:"Peixe e frutos do mar marinados em suco de limão." },
    precio:45000, img:"aperitivo-ceviche", tags:[], badge:"mustTry" },
  { id:"a4", cat:"aperitivos",
    nombre:{ es:"Cóctel de Camarones", en:"Shrimp Cocktail", pt:"Coquetel de Camarão" },
    desc:{ es:"Camarones frescos en salsa cóctel de la casa.", en:"Fresh shrimp tossed in house cocktail sauce.", pt:"Camarões frescos ao molho coquetel da casa." },
    precio:32000, img:"aperitivo-coctel-camarones", tags:[] },
  { id:"a5", cat:"aperitivos",
    nombre:{ es:"Papas con Queso", en:"Cheesy Fries (To Share)", pt:"Batatas com Queijo (Para Compartilhar)" },
    desc:{ es:"Con griot, pollo, chorizo, carne o paisa (extra).", en:"Topped with griot, chicken, chorizo, ground beef, or paisa style (extra).", pt:"Com griot, frango, chorizo, carne moída ou estilo paisa (adicional)." },
    precio:34000, img:"aperitivo-papas-queso", tags:[] },

  // ---- CAFÉ / COFFEE / CAFÉ ----
  { id:"c1", cat:"cafe",
    nombre:{ es:"Espresso", en:"Espresso", pt:"Espresso" },
    desc:{ es:"Café concentrado servido solo.", en:"Single shot of concentrated espresso.", pt:"Café concentrado servido puro." },
    precio:7600, img:"cafe-espresso", tags:[] },
  { id:"c2", cat:"cafe",
    nombre:{ es:"Americano", en:"Americano", pt:"Americano" },
    desc:{ es:"Espresso alargado con agua caliente.", en:"Espresso diluted with hot water.", pt:"Espresso diluído com água quente." },
    precio:7800, img:"cafe-americano", tags:[] },
  { id:"c3", cat:"cafe",
    nombre:{ es:"Capuchino", en:"Cappuccino", pt:"Cappuccino" },
    desc:{ es:"Espresso con leche vaporizada y espuma espesa.", en:"Espresso with steamed milk and thick foam.", pt:"Espresso com leite vaporizado e espuma densa." },
    precio:9800, img:"cafe-capuchino", tags:[] },
  { id:"c4", cat:"cafe",
    nombre:{ es:"Macchiato", en:"Macchiato", pt:"Macchiato" },
    desc:{ es:"Espresso manchado con leche espumada.", en:"Espresso stained with a touch of milk foam.", pt:"Espresso manchado com espuma de leite." },
    precio:9800, img:"cafe-macchiato", tags:[] },
  { id:"c5", cat:"cafe",
    nombre:{ es:"Café Latte", en:"Latte", pt:"Café Latte" },
    desc:{ es:"Café con leche vaporizada suave.", en:"Coffee with smooth steamed milk.", pt:"Café com leite vaporizado suave." },
    precio:10200, img:"cafe-latte", tags:[] },
  { id:"c6", cat:"cafe",
    nombre:{ es:"Flat White", en:"Flat White", pt:"Flat White" },
    desc:{ es:"Doble espresso cubierto con microespuma.", en:"Double espresso topped with silky microfoam.", pt:"Café duplo coberto com microespuma sedosa." },
    precio:10200, img:"cafe-flatwhite", tags:[] },
  { id:"c7", cat:"cafe",
    nombre:{ es:"Chocolate Caliente", en:"Hot Chocolate", pt:"Chocolate Quente" },
    desc:{ es:"Preparado tradicional caliente.", en:"Traditional rich hot chocolate.", pt:"Chocolate quente tradicional e cremoso." },
    precio:10600, img:"cafe-chocolate", tags:[] },

  // ---- BEBIDAS SIN ALCOHOL / NON-ALCOHOLIC DRINKS / BEBIDAS SEM ÁLCOOL ----
  { id:"b1", cat:"bebidas",
    nombre:{ es:"Limonada Natural", en:"Classic Lemonade", pt:"Limonada Natural" },
    desc:{ es:"Limonada fresca hecha al momento.", en:"Freshly squeezed lemonade.", pt:"Limonada fresca feita na hora." },
    precio:8000, img:"bebida-limonada-natural", tags:[] },
  { id:"b2", cat:"bebidas",
    nombre:{ es:"Limonada de Coco", en:"Coconut Lemonade", pt:"Limonada de Coco" },
    desc:{ es:"Limonada cremosa mezclada con leche de coco.", en:"Creamy lemonade blended with coconut milk.", pt:"Limonada cremosa misturada com leite de coco." },
    precio:14000, img:"bebida-limonada-coco", tags:[] },
  { id:"b3", cat:"bebidas",
    nombre:{ es:"Jugos Naturales", en:"Natural Juices", pt:"Sucos Naturais" },
    desc:{ es:"Maracuyá, mango, piña, fresa, banano, níspero, naranja.", en:"Passion fruit, mango, pineapple, strawberry, banana, loquat, orange.", pt:"Maracujá, manga, abacaxi, morango, banana, nêspera, laranja." },
    precio:10000, img:"bebida-jugos-naturales", tags:[] },
  { id:"b8", cat:"bebidas",
    nombre:{ es:"Gaseosa", en:"Soft Drink", pt:"Refrigerante" },
    desc:{ es:"Coca-Cola, Zero, Sprite, Fanta, Canada Dry, Colombiana, Pony Malta.", en:"Coca-Cola, Zero, Sprite, Fanta, Canada Dry, Colombiana, Pony Malta.", pt:"Coca-Cola, Zero, Sprite, Fanta, Canada Dry, Colombiana, Pony Malta." },
    precio:9000, img:"bebida-gaseosas", tags:[] },
  { id:"b9", cat:"bebidas",
    nombre:{ es:"Agua Natural / con Gas", en:"Still or Sparkling Water", pt:"Água Natural / com Gás" },
    desc:{ es:"Botella individual.", en:"Individual bottle.", pt:"Garrafa individual." },
    precio:7000, img:"bebida-agua", tags:[] },

  // ---- PLATOS PRINCIPALES / MAIN DISHES / PRATOS PRINCIPAIS ----
  { id:"p1", cat:"platos",
    nombre:{ es:"Bandeja de Plátano Fritay", en:"Fritay Plantain Platter", pt:"Bandeja de Banana Fritay" },
    desc:{ es:"Plátano frito con carnes y pikliz tradicional.", en:"Fried plantain with meats and traditional pikliz.", pt:"Banana-da-terra frita com carnes e pikliz tradicional." },
    precio:36000, img:"plato-bandeja-fritay", tags:[] },
  { id:"p2", cat:"platos",
    nombre:{ es:"Griot con Pikliz", en:"Griot with Pikliz", pt:"Griot com Pikliz" },
    desc:{ es:"Cerdo marinado y frito con pikliz picante.", en:"Marinated fried pork with spicy pikliz.", pt:"Porco marinado e frito com pikliz picante." },
    precio:29000, img:"plato-griot-pikliz", tags:[] },
  { id:"p3", cat:"platos",
    nombre:{ es:"Pollo Frito Criollo", en:"Creole Fried Chicken", pt:"Frango Frito Crioulo" },
    desc:{ es:"Pollo frito sazonado con especias caribeñas.", en:"Fried chicken seasoned with Creole Caribbean spices.", pt:"Frango frito temperado com especiarias caribenhas." },
    precio:36000, img:"plato-pollo-frito", tags:[] },
  { id:"p4", cat:"platos",
    nombre:{ es:"Sopa Haitiana de Carne", en:"Haitian Beef Soup", pt:"Sopa Haitiana de Carne" },
    desc:{ es:"Sopa sustanciosa tradicional haitiana.", en:"Hearty traditional Haitian beef soup.", pt:"Sopa farta tradicional haitiana de carne." },
    precio:30000, img:"plato-sopa-haitiana", tags:[] },
  { id:"p5", cat:"platos",
    nombre:{ es:"Pescado Entero Frito", en:"Whole Fried Fish", pt:"Peixe Inteiro Frito" },
    desc:{ es:"Pescado del día frito crocante, con acompañamiento.", en:"Crispy whole fried catch of the day, served with a side.", pt:"Peixe do dia frito e crocante, servido com acompanhamento." },
    precio:38000, img:"plato-pescado-frito", tags:[] },
  { id:"p6", cat:"platos",
    nombre:{ es:"Papas con Queso", en:"Cheesy Fries", pt:"Batatas com Queijo" },
    desc:{ es:"Papas fritas cubiertas de queso y su proteína.", en:"Fries topped with cheese and your choice of protein.", pt:"Batatas fritas cobertas com queijo e proteína à escolha." },
    precio:34000, img:"plato-papas-queso", tags:[] },
  { id:"p7", cat:"platos",
    nombre:{ es:"Camarones al Ajillo", en:"Garlic Shrimp", pt:"Camarão ao Alho" },
    desc:{ es:"Salteados en mantequilla, ajo y finas hierbas.", en:"Sautéed in butter, garlic, and fine herbs.", pt:"Salteados na manteiga, alho e ervas finas." },
    precio:42000, img:"plato-camarones-ajillo", tags:[], badge:"chef" },
  { id:"p8", cat:"platos",
    nombre:{ es:"Poke Bowl Vegetariano", en:"Vegetarian Poke Bowl", pt:"Poke Bowl Vegetariano" },
    desc:{ es:"Bowl fresco con vegetales de temporada y granos.", en:"Fresh bowl with seasonal vegetables and grains.", pt:"Bowl fresco com vegetais da estação e grãos." },
    precio:28000, img:"plato-poke-bowl", tags:[] },

  // ---- CARNES Y MARISCOS / MEATS & SEAFOOD / CARNES E FRUTOS DO MAR ----
  { id:"m1", cat:"carnes",
    nombre:{ es:"Pechuga de Pollo a la Plancha", en:"Grilled Chicken Breast", pt:"Peito de Frango Grelhado" },
    desc:{ es:"Pechuga marinada y cocinada a la plancha.", en:"Marinated chicken breast cooked on the grill.", pt:"Peito de frango marinado e grelhado." },
    precio:38000, img:"carnes-pechuga", tags:[] },
  { id:"m2", cat:"carnes",
    nombre:{ es:"Picanha", en:"Picanha Steak", pt:"Picanha" },
    desc:{ es:"Corte premium de res a la brasa.", en:"Premium beef cut grilled over open flame.", pt:"Corte premium de carne bovina grelhado na brasa." },
    precio:58000, img:"carnes-picanha", tags:[], badge:"mustTry" },
  { id:"m3", cat:"carnes",
    nombre:{ es:"Bistec Criollo", en:"Creole Steak", pt:"Bife Crioulo" },
    desc:{ es:"Corte de res cubierto con salsa criolla casera.", en:"Beef steak smothered in homemade Creole sauce.", pt:"Bife bovino coberto com molho crioulo caseiro." },
    precio:45000, img:"carnes-bistec", tags:[] },
  { id:"m4", cat:"carnes",
    nombre:{ es:"Arroz con Camarón", en:"Shrimp Rice", pt:"Arroz com Camarão" },
    desc:{ es:"Arroz caribeño con camarones y especias.", en:"Caribbean rice with shrimp and spices.", pt:"Arroz caribenho com camarão e especiarias." },
    precio:38000, img:"carnes-arroz-camaron", tags:[] },
  { id:"m5", cat:"carnes",
    nombre:{ es:"Lomo Saltado", en:"Stir-Fried Beef", pt:"Lombo Salteado" },
    desc:{ es:"Tiras de lomo salteadas al wok con tomate y cebolla.", en:"Beef strips stir-fried in the wok with tomato and onion.", pt:"Tiras de lombo salteadas no wok com tomate e cebola." },
    precio:55000, img:"carnes-lomo-saltado", tags:[] },
  { id:"m6", cat:"carnes",
    nombre:{ es:"Camarones al Curry con Arroz de Coco", en:"Curry Shrimp with Coconut Rice", pt:"Camarão ao Curry com Arroz de Coco" },
    desc:{ es:"Camarones en salsa cremosa de curry caribeño, servidos sobre arroz de coco.", en:"Shrimp in creamy Caribbean curry sauce, served over coconut rice.", pt:"Camarões em cremoso molho de curry caribenho, servidos sobre arroz de coco." },
    precio:42000, img:"carnes-arroz-camaron", tags:[], badge:"nuevo" },

  // ---- ACOMPAÑAMIENTOS / SIDES / ACOMPANHAMENTOS ----
  { id:"s1", cat:"sides",
    nombre:{ es:"Arroz", en:"Rice", pt:"Arroz" },
    desc:{ es:"Porción individual de arroz blanco.", en:"Individual portion of white rice.", pt:"Porção individual de arroz branco." },
    precio:7000, img:"lado-arroz", tags:[] },
  { id:"s2", cat:"sides",
    nombre:{ es:"Arroz con Frijoles", en:"Rice & Beans", pt:"Arroz com Feijão" },
    desc:{ es:"Guarnición clásica de frijoles con arroz.", en:"Classic side of beans and rice.", pt:"Acompanhamento clássico de feijão com arroz." },
    precio:9000, img:"lado-arroz-frijoles", tags:[] },
  { id:"s3", cat:"sides",
    nombre:{ es:"Arroz de Coco", en:"Coconut Rice", pt:"Arroz de Coco" },
    desc:{ es:"Arroz con coco estilo costeño.", en:"Coastal-style coconut rice.", pt:"Arroz com coco estilo costeño." },
    precio:9000, img:"lado-arroz-coco", tags:[] },
  { id:"s4", cat:"sides",
    nombre:{ es:"Patacones", en:"Fried Plantains", pt:"Patacones" },
    desc:{ es:"Rondas de plátano verde frito.", en:"Rounds of fried green plantain.", pt:"Rodelas de banana-da-terra verde frita." },
    precio:9000, img:"lado-patacones", tags:[] },
  { id:"s5", cat:"sides",
    nombre:{ es:"Papas Fritas", en:"French Fries", pt:"Batatas Fritas" },
    desc:{ es:"Papas fritas clásicas.", en:"Classic crispy fries.", pt:"Batatas fritas clássicas." },
    precio:9000, img:"lado-papas-fritas", tags:[] },
  { id:"s6", cat:"sides",
    nombre:{ es:"Hogao", en:"Hogao Sauce", pt:"Molho Hogao" },
    desc:{ es:"Salsa tradicional colombiana de tomate y cebolla.", en:"Traditional Colombian tomato and onion sauce.", pt:"Molho tradicional colombiano de tomate e cebola." },
    precio:7000, img:"lado-hogao", tags:[] },
  { id:"s7", cat:"sides",
    nombre:{ es:"Ají", en:"Spicy Aji Sauce", pt:"Molho Ají" },
    desc:{ es:"Salsa picante de la casa.", en:"House hot sauce.", pt:"Molho picante da casa." },
    precio:7000, img:"lado-aji", tags:[] },

  // ---- CÓCTELES / COCKTAILS / COQUETÉIS ----
  { id:"k1", cat:"bar", sub:"cocteles",
    nombre:{ es:"Cócteles de la Casa", en:"House Cocktails", pt:"Coquetéis da Casa" },
    desc:{ es:"Mojito, Piña Colada, Margarita, Daiquirí, Cuba Libre, Ponche Caribeño, Canelazo.", en:"Mojito, Piña Colada, Margarita, Daiquiri, Cuba Libre, Caribbean Punch, Canelazo.", pt:"Mojito, Piña Colada, Margarita, Daiquiri, Cuba Libre, Ponche Caribenho, Canelazo." },
    precio:40000, img:"bar-cocteles-casa", tags:[], badge:"favorito" },
  { id:"k2", cat:"bar", sub:"cocteles",
    nombre:{ es:"Coctelería Clásica Premium", en:"Premium Classics", pt:"Coquetelaria Clássica Premium" },
    desc:{ es:"Elaborados con licores seleccionados y recetas clásicas.", en:"Crafted with select spirits and classic recipes.", pt:"Preparados com destilados selecionados e receitas clássicas." },
    precio:42500, img:"bar-cocteleria-premium", tags:[], badge:"bartender" },

  // ---- COCTELERÍA PREMIUM / PREMIUM COCKTAILS / COQUETELARIA PREMIUM ----
  { id:"k3", cat:"bar", sub:"premium",
    nombre:{ es:"Boulevardier", en:"Boulevardier", pt:"Boulevardier" },
    desc:{ es:"Clásico de autor con bourbon, Campari y vermut rojo.", en:"Craft classic with bourbon, Campari, and sweet vermouth.", pt:"Clássico autoral com bourbon, Campari e vermute tinto." },
    precio:45000, img:"bar-cocteleria-premium", tags:[], badge:"bartender" },

  // ---- VINO & SANGRÍA / WINE & SANGRIA / VINHO & SANGRIA ----
  { id:"v1", cat:"bar", sub:"vino",
    nombre:{ es:"Vino por Copa", en:"Wine by the Glass", pt:"Vinho por Taça" },
    desc:{ es:"Tinto, blanco o rosado.", en:"Red, white, or rosé.", pt:"Tinto, branco ou rosé." },
    precio:28000, img:"bar-vino-copa", tags:[] },
  { id:"v2", cat:"bar", sub:"vino",
    nombre:{ es:"Sangría (Jarra)", en:"Sangria (Pitcher)", pt:"Sangria (Jarra)" },
    desc:{ es:"Sangría tinta o blanca con fruta fresca.", en:"Red or white sangria with fresh fruit.", pt:"Sangria tinta ou branca com frutas frescas." },
    precio:75000, img:"bar-sangria", tags:[] },
  { id:"v3", cat:"bar", sub:"vino",
    nombre:{ es:"Finca Las Moras Chardonnay", en:"Finca Las Moras Chardonnay", pt:"Finca Las Moras Chardonnay" },
    desc:{ es:"Vino blanco argentino de San Juan, fresco y aromático con notas de fruta madura.", en:"Argentine white wine from San Juan, crisp and aromatic with ripe fruit notes.", pt:"Vinho branco argentino de San Juan, fresco e aromático com notas de fruta madura." },
    precio:95000, img:"bar-las-moras-chardonnay", tags:[] },
  { id:"v4", cat:"bar", sub:"vino",
    nombre:{ es:"Finca Las Moras Cabernet Sauvignon", en:"Finca Las Moras Cabernet Sauvignon", pt:"Finca Las Moras Cabernet Sauvignon" },
    desc:{ es:"Vino tinto argentino de San Juan, cuerpo intenso con notas a frutos rojos y especias.", en:"Argentine red wine from San Juan, full-bodied with red fruit and spice notes.", pt:"Vinho tinto argentino de San Juan, corpo intenso com notas de frutas vermelhas e especiarias." },
    precio:95000, img:"bar-las-moras-cabernet", tags:[] },
  { id:"v5", cat:"bar", sub:"vino",
    nombre:{ es:"Rosaleda Cabernet Sauvignon", en:"Rosaleda Cabernet Sauvignon", pt:"Rosaleda Cabernet Sauvignon" },
    desc:{ es:"Vino tinto chileno suave y frutal, fácil de disfrutar en cualquier momento.", en:"Smooth, fruit-forward Chilean red wine, easy to enjoy any time.", pt:"Vinho tinto chileno suave e frutado, fácil de apreciar a qualquer momento." },
    precio:70000, img:"bar-rosaleda-cabernet", tags:[] },
  { id:"v6", cat:"bar", sub:"vino",
    nombre:{ es:"Rosaleda Sauvignon Blanc", en:"Rosaleda Sauvignon Blanc", pt:"Rosaleda Sauvignon Blanc" },
    desc:{ es:"Vino blanco chileno fresco y ligero, con notas cítricas y herbales.", en:"Fresh, light Chilean white wine with citrus and herbal notes.", pt:"Vinho branco chileno fresco e leve, com notas cítricas e de ervas." },
    precio:70000, img:"bar-rosaleda-sauvignon-blanc", tags:[] },

  // ---- CERVEZA / BEER / CERVEJA ----
  { id:"z1", cat:"bar", sub:"cerveza",
    nombre:{ es:"Águila Original", en:"Águila Original", pt:"Águila Original" },
    desc:{ es:"La cerveza más querida de Colombia, creada en Barranquilla desde 1913.", en:"Colombia's most beloved beer, brewed in Barranquilla since 1913.", pt:"A cerveja mais querida da Colômbia, criada em Barranquilla desde 1913." },
    precio:15000, img:"bar-aguila-original", tags:[] },
  { id:"z2", cat:"bar", sub:"cerveza",
    nombre:{ es:"Águila Light", en:"Águila Light", pt:"Águila Light" },
    desc:{ es:"La versión ligera de la clásica Águila, mismo sabor con menos calorías.", en:"The light version of the classic Águila — same great taste, fewer calories.", pt:"A versão leve da clássica Águila, o mesmo sabor com menos calorias." },
    precio:15000, img:"bar-aguila-light", tags:[] },
  { id:"z3", cat:"bar", sub:"cerveza",
    nombre:{ es:"Club Colombia Dorada", en:"Club Colombia Golden Lager", pt:"Club Colombia Dourada" },
    desc:{ es:"Lager dorada premium colombiana, maestría cervecera desde 1928.", en:"Colombia's premium golden lager, master-brewed since 1928.", pt:"Lager dourada premium colombiana, maestria cervejeira desde 1928." },
    precio:17000, img:"bar-club-colombia-dorada", tags:[] },
  { id:"z4", cat:"bar", sub:"cerveza",
    nombre:{ es:"Corona", en:"Corona", pt:"Corona" },
    desc:{ es:"Cerveza mexicana ligera y refrescante, ideal con una rodaja de limón.", en:"Light, refreshing Mexican beer, best enjoyed with a lime wedge.", pt:"Cerveja mexicana leve e refrescante, ideal com uma rodela de limão." },
    precio:20000, img:"bar-corona", tags:[] },
  { id:"z5", cat:"bar", sub:"cerveza",
    nombre:{ es:"Stella Artois", en:"Stella Artois", pt:"Stella Artois" },
    desc:{ es:"Lager belga premium, elaborada bajo una tradición cervecera que se remonta a 1366.", en:"Premium Belgian lager, brewed under a tradition dating back to 1366.", pt:"Lager belga premium, elaborada sob uma tradição cervejeira que remonta a 1366." },
    precio:20000, img:"bar-stella-artois", tags:[] },
  { id:"z6", cat:"bar", sub:"cerveza",
    nombre:{ es:"Cerveza Modelo Especial", en:"Modelo Especial", pt:"Cerveja Modelo Especial" },
    desc:{ es:"Lager mexicana de cuerpo medio, refrescante desde 1925.", en:"Medium-bodied Mexican lager, refreshing since 1925.", pt:"Lager mexicana de corpo médio, refrescante desde 1925." },
    precio:30000, img:"bar-modelo-especial", tags:[] },
  { id:"z7", cat:"bar", sub:"cerveza",
    nombre:{ es:"Smirnoff Ice Manzana Verde", en:"Smirnoff Ice Green Apple", pt:"Smirnoff Ice Maçã Verde" },
    desc:{ es:"Mezcla lista para tomar de vodka Smirnoff con un toque burbujeante de manzana verde.", en:"Ready-to-drink Smirnoff vodka mix with a bubbly green apple twist.", pt:"Mistura pronta para beber de vodka Smirnoff com um toque borbulhante de maçã verde." },
    precio:19000, img:"bar-smirnoff-ice", tags:[] },
  { id:"z8", cat:"bar", sub:"cerveza",
    nombre:{ es:"Refajo", en:"Refajo", pt:"Refajo" },
    desc:{ es:"Mezcla refrescante de cerveza y gaseosa Colombiana.", en:"Refreshing blend of beer and Colombiana soda.", pt:"Mistura refrescante de cerveja com refrigerante Colombiana." },
    precio:18000, img:"bar-refajo", tags:[] },
  { id:"z9", cat:"bar", sub:"cerveza",
    nombre:{ es:"Michelada Colombiana", en:"Colombian Michelada", pt:"Michelada Colombiana" },
    desc:{ es:"Borde de sal y limón fresco.", en:"Salt-rimmed with fresh lime.", pt:"Borda de sal com limão fresco." },
    precio:18000, img:"bar-michelada", tags:[] },

  // ---- LICORES / SPIRITS / DESTILADOS ----
  { id:"l1", cat:"bar", sub:"licores",
    nombre:{ es:"Ron Viejo de Caldas Añejo 3 Años", en:"Ron Viejo de Caldas Añejo 3 Años", pt:"Ron Viejo de Caldas Añejo 3 Años" },
    desc:{ es:"El ron colombiano #1 en ventas del país, añejado 3 años, suave y de sabor tradicional.", en:"Colombia's #1 selling rum, aged 3 years for a smooth, traditional flavor.", pt:"O rum colombiano mais vendido do país, envelhecido 3 anos, suave e de sabor tradicional." },
    precio:25000, precioBotella:240000, img:"bar-ron-viejo-caldas", tags:[] },
  { id:"l2", cat:"bar", sub:"licores",
    nombre:{ es:"Buchanan's DeLuxe 12 Años", en:"Buchanan's DeLuxe 12-Year", pt:"Buchanan's DeLuxe 12 Anos" },
    desc:{ es:"Whisky escocés mezclado, añejado 12 años, elaborado con pasión desde 1884.", en:"Blended Scotch whisky, aged 12 years, crafted with passion since 1884.", pt:"Whisky escocês misturado, envelhecido 12 anos, elaborado com paixão desde 1884." },
    precio:32000, precioBotella:300000, img:"bar-buchanans-12", tags:[] },
  { id:"l3", cat:"bar", sub:"licores",
    nombre:{ es:"Grand Old Parr 12 Años", en:"Grand Old Parr 12-Year", pt:"Grand Old Parr 12 Anos" },
    desc:{ es:"Whisky escocés mezclado añejado 12 años, homenaje al legendario Thomas Parr desde 1871.", en:"Blended Scotch whisky aged 12 years, a tribute to the legendary Thomas Parr since 1871.", pt:"Whisky escocês misturado envelhecido 12 anos, homenagem ao lendário Thomas Parr desde 1871." },
    precio:32000, precioBotella:300000, img:"bar-old-parr-12", tags:[] },
  { id:"l4", cat:"bar", sub:"licores",
    nombre:{ es:"Johnnie Walker Black Label", en:"Johnnie Walker Black Label", pt:"Johnnie Walker Black Label" },
    desc:{ es:"Whisky escocés mezclado añejado 12 años, ícono mundial de la coctelería.", en:"Blended Scotch whisky aged 12 years, a world icon of fine whisky.", pt:"Whisky escocês misturado envelhecido 12 anos, ícone mundial da coquetelaria." },
    precio:32000, precioBotella:300000, img:"bar-black-label", tags:[] },
  { id:"l5", cat:"bar", sub:"licores",
    nombre:{ es:"Buchanan's Master", en:"Buchanan's Master", pt:"Buchanan's Master" },
    desc:{ es:"Whisky escocés premium, mezcla superior con notas dulces y amaderadas. Solo botella.", en:"Premium blended Scotch whisky with sweet, woody notes. Bottle only.", pt:"Whisky escocês premium, mistura superior com notas doces e amadeiradas. Somente garrafa." },
    precio:null, precioBotella:420000, img:"bar-buchanans-master", tags:[] },
  { id:"l6", cat:"bar", sub:"licores",
    nombre:{ es:"Tanqueray London Dry Gin", en:"Tanqueray London Dry Gin", pt:"Tanqueray London Dry Gin" },
    desc:{ es:"Gin inglés London Dry, receta de cuatro botánicos perfectamente balanceados desde 1830.", en:"English London Dry gin, a signature recipe of four perfectly balanced botanicals since 1830.", pt:"Gin inglês London Dry, receita de quatro botânicos perfeitamente equilibrados desde 1830." },
    precio:30000, precioBotella:280000, img:"bar-tanqueray", tags:[] },
  { id:"l7", cat:"bar", sub:"licores",
    nombre:{ es:"Aguardiente Amarillo de Manzanares", en:"Aguardiente Amarillo de Manzanares", pt:"Aguardiente Amarillo de Manzanares" },
    desc:{ es:"Aguardiente colombiano sin azúcar, destilado de caña, pionero de los amarillos desde 1885.", en:"Sugar-free Colombian aguardiente, cane-distilled — the pioneer of Colombia's 'yellow' aguardientes since 1885.", pt:"Aguardente colombiana sem açúcar, destilada de cana-de-açúcar, pioneira dos amarelos desde 1885." },
    precio:25000, precioBotella:250000, img:"bar-aguardiente-amarillo", tags:[] },
];

const CATEGORIES = [
  { id:"desayuno", nombre:{ es:"Desayuno", en:"Breakfast", pt:"Café da Manhã" } },
  { id:"aperitivos", nombre:{ es:"Aperitivos", en:"Starters", pt:"Aperitivos" } },
  { id:"cafe", nombre:{ es:"Café", en:"Coffee", pt:"Café" } },
  { id:"bebidas", nombre:{ es:"Bebidas sin Alcohol", en:"Non-Alcoholic Drinks", pt:"Bebidas sem Álcool" } },
  { id:"platos", nombre:{ es:"Platos Principales", en:"Main Dishes", pt:"Pratos Principais" } },
  { id:"carnes", nombre:{ es:"Carnes y Mariscos", en:"Meats & Seafood", pt:"Carnes e Frutos do Mar" } },
  { id:"sides", nombre:{ es:"Acompañamientos", en:"Sides", pt:"Acompanhamentos" } },
  { id:"bar", nombre:{ es:"Bar & Coctelería", en:"Bar & Cocktails", pt:"Bar & Coquetelaria" } },
];

// Subgrupos dentro de la categoría "bar"
const BAR_SUBS = {
  cocteles: { es:"Cócteles", en:"Cocktails", pt:"Coquetéis" },
  premium: { es:"Coctelería Premium", en:"Premium Cocktails", pt:"Coquetelaria Premium" },
  vino: { es:"Vino & Sangría", en:"Wine & Sangria", pt:"Vinho & Sangria" },
  cerveza: { es:"Cerveza", en:"Beer", pt:"Cerveja" },
  licores: { es:"Licores", en:"Spirits", pt:"Destilados" },
};
