// Datos del menú - Azul Caribe Lounge
// tags: reservado para uso futuro (filtros eliminados del menú)
//
// IMPORTANTE sobre el tag "sinAlcohol":
// Este tag se usa SOLO para bebidas (café y bebidas sin alcohol) que no
// contienen alcohol. No se aplica a platos de comida — aunque un plato no
// lleve alcohol, no es una "bebida sin alcohol", así que no debe llevar
// este tag. Esto es a propósito para que el filtro "Sin Alcohol" muestre
// únicamente bebidas, nunca comida.
//
// IDIOMAS: "nombre" y "desc" son objetos {es, en, pt, fr}. Para editar una
// traducción, cambia solo el texto dentro de las comillas de ese idioma.
// "badge" (opcional) es una clave que se traduce en i18n.js (BADGE_LABELS):
// "favorito" | "mustTry" | "chef" (platos de cocina) | "bartender" (cócteles/bar) | "nuevo".
const MENU_DATA = [
  // ---- DESAYUNO / MORNING / CAFÉ DA MANHÃ / PETIT-DÉJEUNER ----
  { id:"d1", cat:"desayuno",
    nombre:{ es:"Tortilla de Queso", en:"Cheese Omelet", pt:"Omelete de Queijo", fr:"Omelette au Fromage" },
    desc:{ es:"Esponjosa tortilla de queso servida con tocino, salchicha y papas.", en:"Fluffy cheese omelet served with bacon, sausage, and potatoes.", pt:"Omelete fofo de queijo servido com bacon, linguiça e batatas.", fr:"Omelette moelleuse au fromage servie avec bacon, saucisse et pommes de terre." },
    precio:24000, img:"desayuno-tortilla-queso", tags:[] },
  { id:"d4", cat:"desayuno",
    nombre:{ es:"Empanadas de Griot y Queso Costeño", en:"Griot & Costeño Cheese Empanadas", pt:"Empanadas de Griot e Queijo Costeño", fr:"Empanadas de Griot et Fromage Côtier" },
    desc:{ es:"Empanadas rellenas de cerdo griot y queso costeño.", en:"Empanadas filled with griot pork and coastal cheese.", pt:"Empanadas recheadas com porco griot e queijo costeño.", fr:"Empanadas farcies de porc griot et de fromage côtier." },
    precio:26000, img:"desayuno-empanadas", tags:[], badge:"favorito" },
  { id:"d6", cat:"desayuno",
    nombre:{ es:"Adicional de Queso", en:"Extra Cheese", pt:"Adicional de Queijo", fr:"Supplément de Fromage" },
    desc:{ es:"Porción extra de queso para acompañar tu desayuno.", en:"Extra portion of cheese to add to your breakfast.", pt:"Porção extra de queijo para acompanhar seu café da manhã.", fr:"Portion supplémentaire de fromage pour accompagner votre petit-déjeuner." },
    precio:5000, img:"aperitivo-papas-queso", tags:[] },
  { id:"d7", cat:"desayuno",
    nombre:{ es:"Desayuno Completo", en:"Full Breakfast", pt:"Café da Manhã Completo", fr:"Petit-Déjeuner Complet" },
    desc:{ es:"Huevos revueltos, chorizo, tocino y sándwich de jamón y queso a la plancha, acompañado de un bowl de fruta fresca.", en:"Scrambled eggs, sausage, bacon, and a grilled ham and cheese sandwich, served with a fresh fruit bowl.", pt:"Ovos mexidos, linguiça, bacon e sanduíche de presunto e queijo na chapa, acompanhado de um bowl de fruta fresca.", fr:"Œufs brouillés, saucisse, bacon et sandwich au jambon et fromage grillé, servi avec un bol de fruits frais." },
    precio:25000, img:"desayuno-completo", tags:[] },
  { id:"d8", cat:"desayuno",
    nombre:{ es:"Arepa con Griot & Ahogao", en:"Arepa with Griot & Ahogao", pt:"Arepa com Griot & Ahogao", fr:"Arepa au Griot & Ahogao" },
    desc:{ es:"Arepa rellena de cerdo crujiente, acompañada de nuestro ahogao.", en:"Corn arepa stuffed with crispy pork, served with our ahogao sauce.", pt:"Arepa recheada com porco crocante, acompanhada do nosso ahogao.", fr:"Arepa de maïs farcie de porc croustillant, accompagnée de notre sauce ahogao." },
    precio:28000, img:"desayuno-arepas-grislet", tags:[], badge:"nuevo" },
  { id:"d10", cat:"desayuno",
    nombre:{ es:"Huevos al Gusto", en:"Eggs Your Way", pt:"Ovos ao Seu Gosto", fr:"Œufs à Votre Façon" },
    desc:{ es:"Pericos, fritos u omelette. Acompañados de arepa, pan o patacón.", en:"Scrambled, fried or omelette-style, served with arepa, bread or patacón.", pt:"Mexidos, fritos ou omelete. Acompanhados de arepa, pão ou patacón.", fr:"Brouillés, frits ou en omelette. Accompagnés d'arepa, de pain ou de patacón." },
    precio:15000, img:"desayuno-tortilla", tags:[], badge:"nuevo" },

  // ---- APERITIVOS PARA COMPARTIR / STARTERS / APERITIVOS / ENTRÉES ----
  { id:"a1", cat:"aperitivos",
    nombre:{ es:"Patacones", en:"Fried Green Plantains", pt:"Patacones", fr:"Patacones" },
    desc:{ es:"Patacones crocantes acompañados de ahogao, guacamole o suero.", en:"Crispy fried plantains served with ahogao, guacamole or suero.", pt:"Patacones crocantes acompanhados de ahogao, guacamole ou suero.", fr:"Patacones croustillants accompagnés d'ahogao, de guacamole ou de suero." },
    precio:17000, img:"aperitivo-patacones", tags:[] },
  { id:"a2", cat:"aperitivos",
    nombre:{ es:"Aborrajados Haitianos", en:"Haitian Aborrajados", pt:"Aborrajados Haitianos", fr:"Aborrajados Haïtiens" },
    desc:{ es:"Plátano maduro relleno de queso y griot de cerdo.", en:"Sweet plantain stuffed with cheese and pork griot.", pt:"Banana-da-terra madura recheada com queijo e griot de porco.", fr:"Banane plantain mûre farcie de fromage et de griot de porc." },
    precio:24000, img:"aperitivo-aborrajados", tags:[] },
  { id:"a3", cat:"aperitivos",
    nombre:{ es:"Ceviche Mixto", en:"Mixed Ceviche", pt:"Ceviche Misto", fr:"Ceviche Mixte" },
    desc:{ es:"Pescado y mariscos marinados en jugo de limón.", en:"Fish and seafood cured in fresh lime juice.", pt:"Peixe e frutos do mar marinados em suco de limão.", fr:"Poisson et fruits de mer marinés dans du jus de citron vert." },
    precio:45000, img:"aperitivo-ceviche", tags:[], badge:"mustTry" },
  { id:"a4", cat:"aperitivos",
    nombre:{ es:"Cóctel de Camarones", en:"Shrimp Cocktail", pt:"Coquetel de Camarão", fr:"Cocktail de Crevettes" },
    desc:{ es:"Camarones frescos en salsa cóctel de la casa.", en:"Fresh shrimp tossed in house cocktail sauce.", pt:"Camarões frescos ao molho coquetel da casa.", fr:"Crevettes fraîches dans une sauce cocktail maison." },
    precio:32000, img:"aperitivo-coctel-camarones", tags:[] },
  { id:"a5", cat:"aperitivos",
    nombre:{ es:"Papas con Queso", en:"Cheesy Fries (To Share)", pt:"Batatas com Queijo (Para Compartilhar)", fr:"Frites au Fromage (à Partager)" },
    desc:{ es:"Con griot, pollo, chorizo, carne o paisa (extra).", en:"Topped with griot, chicken, chorizo, ground beef, or paisa style (extra).", pt:"Com griot, frango, chorizo, carne moída ou estilo paisa (adicional).", fr:"Avec griot, poulet, chorizo, bœuf haché ou style paisa (supplément)." },
    precio:34000, img:"papas-queso-compartir", tags:[] },

  // ---- CAFÉ / COFFEE / CAFÉ / CAFÉ ----
  { id:"c1", cat:"cafe",
    nombre:{ es:"Café Espresso", en:"Espresso", pt:"Café Espresso", fr:"Espresso" },
    desc:{ es:"Café concentrado servido solo.", en:"Single shot of concentrated espresso.", pt:"Café concentrado servido puro.", fr:"Café concentré servi seul." },
    precio:7600, img:"cafe-espresso", tags:[] },
  { id:"c2", cat:"cafe",
    nombre:{ es:"Café Americano", en:"Americano", pt:"Café Americano", fr:"Americano" },
    desc:{ es:"Espresso alargado con agua caliente.", en:"Espresso diluted with hot water.", pt:"Espresso diluído com água quente.", fr:"Espresso allongé à l'eau chaude." },
    precio:7800, img:"cafe-americano", tags:[] },
  { id:"c3", cat:"cafe",
    nombre:{ es:"Capuchino", en:"Cappuccino", pt:"Cappuccino", fr:"Cappuccino" },
    desc:{ es:"Espresso con leche vaporizada y espuma espesa.", en:"Espresso with steamed milk and thick foam.", pt:"Espresso com leite vaporizado e espuma densa.", fr:"Espresso avec lait vaporisé et mousse épaisse." },
    precio:9800, img:"cafe-capuchino", tags:[] },
  { id:"c4", cat:"cafe",
    nombre:{ es:"Macchiato", en:"Macchiato", pt:"Macchiato", fr:"Macchiato" },
    desc:{ es:"Espresso manchado con leche espumada.", en:"Espresso stained with a touch of milk foam.", pt:"Espresso manchado com espuma de leite.", fr:"Espresso taché d'une touche de mousse de lait." },
    precio:9800, img:"cafe-macchiato", tags:[] },
  { id:"c5", cat:"cafe",
    nombre:{ es:"Café Latte", en:"Latte", pt:"Café Latte", fr:"Café Latte" },
    desc:{ es:"Café con leche vaporizada suave.", en:"Coffee with smooth steamed milk.", pt:"Café com leite vaporizado suave.", fr:"Café avec lait vaporisé onctueux." },
    precio:10200, img:"cafe-latte", tags:[] },
  { id:"c6", cat:"cafe",
    nombre:{ es:"Flat White", en:"Flat White", pt:"Flat White", fr:"Flat White" },
    desc:{ es:"Doble espresso cubierto con microespuma.", en:"Double espresso topped with silky microfoam.", pt:"Café duplo coberto com microespuma sedosa.", fr:"Double espresso recouvert de microfoam soyeuse." },
    precio:10200, img:"cafe-flatwhite", tags:[] },
  { id:"c7", cat:"cafe",
    nombre:{ es:"Chocolate Caliente", en:"Hot Chocolate", pt:"Chocolate Quente", fr:"Chocolat Chaud" },
    desc:{ es:"Preparado tradicional caliente.", en:"Traditional rich hot chocolate.", pt:"Chocolate quente tradicional e cremoso.", fr:"Préparation traditionnelle chaude et onctueuse." },
    precio:10600, img:"cafe-chocolate", tags:[] },

  // ---- BEBIDAS SIN ALCOHOL / NON-ALCOHOLIC DRINKS / BEBIDAS SEM ÁLCOOL / BOISSONS SANS ALCOOL ----
  { id:"b1", cat:"bebidas",
    nombre:{ es:"Limonada Natural", en:"Classic Lemonade", pt:"Limonada Natural", fr:"Citronnade Nature" },
    desc:{ es:"Limonada fresca hecha al momento.", en:"Freshly squeezed lemonade.", pt:"Limonada fresca feita na hora.", fr:"Citronnade fraîche préparée minute." },
    precio:10000, img:"bebida-limonada-natural", tags:[] },
  { id:"b2", cat:"bebidas",
    nombre:{ es:"Limonada de Coco", en:"Coconut Lemonade", pt:"Limonada de Coco", fr:"Citronnade à la Noix de Coco" },
    desc:{ es:"Limonada cremosa mezclada con leche de coco.", en:"Creamy lemonade blended with coconut milk.", pt:"Limonada cremosa misturada com leite de coco.", fr:"Citronnade crémeuse mélangée avec du lait de coco." },
    precio:14000, img:"bebida-limonada-coco", tags:[] },
  { id:"b3", cat:"bebidas",
    nombre:{ es:"Jugos Naturales (en agua)", en:"Natural Juices (in water)", pt:"Sucos Naturais (na água)", fr:"Jus Naturels (à l'eau)" },
    desc:{ es:"Maracuyá, mango, piña, fresa, banano, níspero, naranja.", en:"Passion fruit, mango, pineapple, strawberry, banana, loquat, orange.", pt:"Maracujá, manga, abacaxi, morango, banana, nêspera, laranja.", fr:"Fruit de la passion, mangue, ananas, fraise, banane, nèfle, orange." },
    precio:10000, img:"bebida-jugos-naturales", tags:[] },
  { id:"b8", cat:"bebidas",
    nombre:{ es:"Gaseosas", en:"Soft Drinks", pt:"Refrigerantes", fr:"Sodas" },
    desc:{ es:"Coca-Cola, Coca-Cola Zero, Colombiana, Pony Malta, Soda Bretaña, Ginger Ale.", en:"Coca-Cola, Coca-Cola Zero, Colombiana, Pony Malta, Soda Bretaña, Ginger Ale.", pt:"Coca-Cola, Coca-Cola Zero, Colombiana, Pony Malta, Soda Bretaña, Ginger Ale.", fr:"Coca-Cola, Coca-Cola Zero, Colombiana, Pony Malta, Soda Bretaña, Ginger Ale." },
    precio:9000, img:"bebida-gaseosas", tags:[] },
  { id:"b9", cat:"bebidas",
    nombre:{ es:"Agua Natural o con Gas", en:"Still or Sparkling Water", pt:"Água Natural ou com Gás", fr:"Eau Plate ou Gazeuse" },
    desc:{ es:"Botella individual.", en:"Individual bottle.", pt:"Garrafa individual.", fr:"Bouteille individuelle." },
    precio:9000, img:"bebida-agua", tags:[] },

  // ---- PLATOS PRINCIPALES / MAIN DISHES / PRATOS PRINCIPAIS / PLATS PRINCIPAUX ----
  { id:"p1", cat:"platos",
    nombre:{ es:"Bandeja de Plátano Fritay", en:"Fritay Plantain Platter", pt:"Bandeja de Banana Fritay", fr:"Plateau de Plantain Fritay" },
    desc:{ es:"Plátano maduro frito, acompañado de carne y pikliz tradicional.", en:"Fried ripe plantain served with meat and traditional pikliz.", pt:"Banana-da-terra madura frita, acompanhada de carne e pikliz tradicional.", fr:"Plantain mûr frit, servi avec de la viande et du pikliz traditionnel." },
    precio:30000, img:"plato-bandeja-fritay", tags:[] },
  { id:"p2", cat:"platos",
    nombre:{ es:"Griot con Pikliz", en:"Griot with Pikliz", pt:"Griot com Pikliz", fr:"Griot au Pikliz" },
    desc:{ es:"Cerdo marinado y frito, servido con pikliz picante.", en:"Fried marinated pork chunks with spicy pikliz slaw.", pt:"Porco marinado e frito, servido com pikliz picante.", fr:"Porc mariné et frit, servi avec du pikliz épicé." },
    precio:29000, img:"plato-griot-pikliz", tags:[] },
  { id:"p3", cat:"platos",
    nombre:{ es:"Pollo Frito Criollo", en:"Creole Fried Chicken", pt:"Frango Frito Crioulo", fr:"Poulet Frit Créole" },
    desc:{ es:"Pollo frito sazonado con especias caribeñas.", en:"Fried chicken seasoned with Creole Caribbean spices.", pt:"Frango frito temperado com especiarias caribenhas.", fr:"Poulet frit assaisonné d'épices caribéennes." },
    precio:30000, img:"plato-pollo-frito", tags:[] },
  { id:"p4", cat:"platos",
    nombre:{ es:"Sopa Haitiana de Carne", en:"Haitian Beef Soup", pt:"Sopa Haitiana de Carne", fr:"Soupe Haïtienne à la Viande" },
    desc:{ es:"Una preparación tradicional de inspiración haitiana.", en:"A traditional Haitian-inspired preparation.", pt:"Uma preparação tradicional de inspiração haitiana.", fr:"Une préparation traditionnelle d'inspiration haïtienne." },
    precio:20000, img:"plato-sopa-haitiana", tags:[] },
  { id:"p5", cat:"platos",
    nombre:{ es:"Pesca del Día", en:"Catch of the Day", pt:"Pesca do Dia", fr:"Pêche du Jour" },
    desc:{ es:"La pesca seleccionada del día, preparada al estilo Azul Caribe.", en:"The day's selected catch, prepared Azul Caribe style.", pt:"A pesca selecionada do dia, preparada ao estilo Azul Caribe.", fr:"La pêche sélectionnée du jour, préparée à la façon Azul Caribe." },
    precio:35000, img:"plato-pescado-frito", tags:[] },
  { id:"p6", cat:"platos",
    nombre:{ es:"Papas con Queso", en:"Cheesy Fries", pt:"Batatas com Queijo", fr:"Frites au Fromage" },
    desc:{ es:"Papas fritas cubiertas de queso y su proteína.", en:"Fries topped with cheese and your choice of protein.", pt:"Batatas fritas cobertas com queijo e proteína à escolha.", fr:"Frites recouvertes de fromage et de la protéine de votre choix." },
    precio:34000, img:"plato-papas-queso", tags:[] },
  { id:"p7", cat:"platos",
    nombre:{ es:"Camarones al Ajillo", en:"Garlic Shrimp", pt:"Camarão ao Alho", fr:"Crevettes à l'Ail" },
    desc:{ es:"Salteados en mantequilla, ajo y finas hierbas.", en:"Sautéed in butter, garlic, and fine herbs.", pt:"Salteados na manteiga, alho e ervas finas.", fr:"Sautées au beurre, à l'ail et aux fines herbes." },
    precio:38000, img:"plato-camarones-ajillo", tags:[], badge:"chef" },
  { id:"p8", cat:"platos",
    nombre:{ es:"Poke Bowl Vegetariano", en:"Vegetarian Poke Bowl", pt:"Poke Bowl Vegetariano", fr:"Poke Bowl Végétarien" },
    desc:{ es:"Bowl fresco con vegetales de temporada y granos.", en:"Fresh bowl with seasonal vegetables and grains.", pt:"Bowl fresco com vegetais da estação e grãos.", fr:"Bol frais aux légumes de saison et céréales." },
    precio:28000, img:"plato-poke-bowl", tags:[] },

  // ---- CARNES Y MARISCOS / MEATS & SEAFOOD / CARNES E FRUTOS DO MAR / VIANDES ET FRUITS DE MER ----
  { id:"m1", cat:"carnes",
    nombre:{ es:"Pechuga de Pollo a la Plancha", en:"Grilled Chicken Breast", pt:"Peito de Frango Grelhado", fr:"Poitrine de Poulet Grillée" },
    desc:{ es:"Pechuga marinada y cocinada a la plancha.", en:"Seasoned grilled chicken breast.", pt:"Peito de frango marinado e grelhado.", fr:"Poitrine marinée et cuite à la plancha." },
    precio:28000, img:"carnes-pechuga", tags:[] },
  { id:"m2", cat:"carnes",
    nombre:{ es:"Picanha", en:"Picanha Steak", pt:"Picanha", fr:"Picanha" },
    desc:{ es:"Corte premium de res a la brasa.", en:"Premium beef cut grilled over open flame.", pt:"Corte premium de carne bovina grelhado na brasa.", fr:"Coupe de bœuf premium grillée au feu de bois." },
    precio:58000, img:"carnes-picanha", tags:[], badge:"mustTry" },
  { id:"m3", cat:"carnes",
    nombre:{ es:"Bistec Criollo de Lomo", en:"Creole Loin Steak", pt:"Bife Crioulo de Lombo", fr:"Bavette Créole" },
    desc:{ es:"Corte de res cubierto con salsa criolla casera de tomate y cebolla.", en:"Beef loin smothered in homemade Creole tomato and onion sauce.", pt:"Corte de lombo bovino coberto com molho crioulo caseiro de tomate e cebola.", fr:"Pièce de bœuf nappée de sauce créole maison à la tomate et à l'oignon." },
    precio:30000, img:"carnes-bistec", tags:[] },
  { id:"m4", cat:"carnes",
    nombre:{ es:"Arroz con Camarón", en:"Shrimp Rice", pt:"Arroz com Camarão", fr:"Riz aux Crevettes" },
    desc:{ es:"Arroz caribeño con camarones y especias.", en:"Caribbean rice with shrimp and spices.", pt:"Arroz caribenho com camarão e especiarias.", fr:"Riz caribéen aux crevettes et épices." },
    precio:38000, img:"carnes-arroz-camaron", tags:[] },
  { id:"m5", cat:"carnes",
    nombre:{ es:"Lomo Saltado", en:"Stir-Fried Beef Loin", pt:"Lombo Salteado", fr:"Lomo Saltado" },
    desc:{ es:"Tiras de lomo salteadas al wok con tomate y cebolla.", en:"Sautéed beef strips with onions and tomatoes.", pt:"Tiras de lombo salteadas no wok com tomate e cebola.", fr:"Lanières de bœuf sautées au wok avec tomate et oignon." },
    precio:38000, img:"carnes-lomo-saltado", tags:[] },
  { id:"m6", cat:"carnes",
    nombre:{ es:"Camarones al Curry con Arroz de Coco", en:"Curry Shrimp with Coconut Rice", pt:"Camarão ao Curry com Arroz de Coco", fr:"Crevettes au Curry et Riz à la Noix de Coco" },
    desc:{ es:"Camarones en salsa cremosa de curry caribeño, servidos sobre arroz de coco.", en:"Shrimp in creamy Caribbean curry sauce, served over coconut rice.", pt:"Camarões em cremoso molho de curry caribenho, servidos sobre arroz de coco.", fr:"Crevettes dans une sauce crémeuse au curry caribéen, servies sur riz à la noix de coco." },
    precio:38000, img:"carnes-camarones-curry-coco", tags:[], badge:"nuevo" },

  // ---- ACOMPAÑAMIENTOS / SIDES / ACOMPANHAMENTOS / ACCOMPAGNEMENTS ----
  { id:"s1", cat:"sides",
    nombre:{ es:"Arroz Blanco", en:"White Rice", pt:"Arroz Branco", fr:"Riz Blanc" },
    desc:{ es:"Porción individual de arroz blanco.", en:"Single serving of white rice.", pt:"Porção individual de arroz branco.", fr:"Portion individuelle de riz blanc." },
    precio:7000, img:"lado-arroz", tags:[] },
  { id:"s2", cat:"sides",
    nombre:{ es:"Arroz de Frijol", en:"Bean Rice", pt:"Arroz de Feijão", fr:"Riz aux Haricots" },
    desc:{ es:"Guarnición clásica de frijoles con arroz.", en:"Classic side of rice with beans.", pt:"Acompanhamento clássico de feijão com arroz.", fr:"Accompagnement classique de haricots au riz." },
    precio:9000, img:"lado-arroz-frijoles", tags:[] },
  { id:"s3", cat:"sides",
    nombre:{ es:"Arroz de Coco", en:"Coconut Rice", pt:"Arroz de Coco", fr:"Riz à la Noix de Coco" },
    desc:{ es:"Arroz con coco estilo costeño.", en:"Coastal-style coconut rice.", pt:"Arroz com coco estilo costeño.", fr:"Riz à la noix de coco façon côtière." },
    precio:9000, img:"lado-arroz-coco", tags:[] },
  { id:"s4", cat:"sides",
    nombre:{ es:"Patacones (Porción)", en:"Fried Plantains (Side)", pt:"Patacones (Porção)", fr:"Patacones (Portion)" },
    desc:{ es:"Rondas de plátano verde frito.", en:"Crispy fried plantain rounds.", pt:"Rodelas de banana-da-terra verde frita.", fr:"Rondelles de plantain vert frit." },
    precio:5000, img:"lado-patacones", tags:[] },
  { id:"s5", cat:"sides",
    nombre:{ es:"Papas Fritas", en:"French Fries", pt:"Batatas Fritas", fr:"Frites" },
    desc:{ es:"Papas fritas clásicas.", en:"Classic crispy fries.", pt:"Batatas fritas clássicas.", fr:"Frites classiques et croustillantes." },
    precio:9000, img:"lado-papas-fritas", tags:[] },
  { id:"s8", cat:"sides",
    nombre:{ es:"Papas Casco", en:"Wedge Fries", pt:"Batatas Rústicas", fr:"Pommes de Terre Rustiques" },
    desc:{ es:"Papas criollas en casco fritas.", en:"Crispy wedge-cut fried potatoes.", pt:"Batatas rústicas fritas.", fr:"Pommes de terre créoles frites en quartiers." },
    precio:8000, img:"lado-papas-casco", tags:[], badge:"nuevo" },
  { id:"s6", cat:"sides",
    nombre:{ es:"Hogao", en:"Hogao Sauce", pt:"Molho Hogao", fr:"Sauce Hogao" },
    desc:{ es:"Salsa tradicional colombiana de tomate y cebolla.", en:"Traditional Colombian tomato and onion sauce.", pt:"Molho tradicional colombiano de tomate e cebola.", fr:"Sauce traditionnelle colombienne à la tomate et à l'oignon." },
    precio:7000, img:"lado-hogao", tags:[] },
  { id:"s7", cat:"sides",
    nombre:{ es:"Ají", en:"Spicy Aji Sauce", pt:"Molho Ají", fr:"Sauce Piquante Ají" },
    desc:{ es:"Salsa picante de la casa.", en:"House hot sauce.", pt:"Molho picante da casa.", fr:"Sauce piquante maison." },
    precio:7000, img:"lado-aji", tags:[] },

  // ---- COCTELERÍA CLÁSICA / CLASSIC COCKTAILS / COQUETELARIA CLÁSSICA / COCKTAILS CLASSIQUES ----
  // "img" = foto en reposo · "img2" = foto con la "explosión" (se ve al tocar la tarjeta).
  { id:"kc1", cat:"bar", sub:"cocteles",
    nombre:{ es:"Mojito", en:"Mojito", pt:"Mojito", fr:"Mojito" },
    desc:{ es:"Ron blanco, hierbabuena, lima, azúcar y soda.", en:"White rum, mint, lime, sugar and soda.", pt:"Rum branco, hortelã, limão, açúcar e soda.", fr:"Rhum blanc, menthe, citron vert, sucre et soda." },
    precio:40000, img:"bar-mojito-v2", img2:"bar-mojito-x", tags:[], badge:"favorito" },
  { id:"kc2", cat:"bar", sub:"cocteles",
    nombre:{ es:"Piña Colada", en:"Piña Colada", pt:"Piña Colada", fr:"Piña Colada" },
    desc:{ es:"Ron, crema de coco y piña.", en:"Rum, coconut cream and pineapple.", pt:"Rum, creme de coco e abacaxi.", fr:"Rhum, crème de coco et ananas." },
    precio:40000, img:"bar-pina-colada-v2", img2:"bar-pina-colada-x", tags:[] },
  { id:"kc3", cat:"bar", sub:"cocteles",
    nombre:{ es:"Margarita Clásica", en:"Classic Margarita", pt:"Margarita Clássica", fr:"Margarita Classique" },
    desc:{ es:"Tequila, triple sec y jugo de limón.", en:"Tequila, triple sec and lime juice.", pt:"Tequila, triple sec e suco de limão.", fr:"Tequila, triple sec et jus de citron vert." },
    precio:40000, img:"bar-margarita-v2", img2:"bar-margarita-x", tags:[] },
  { id:"kc4", cat:"bar", sub:"cocteles",
    nombre:{ es:"Margarita de Maracuyá", en:"Passion Fruit Margarita", pt:"Margarita de Maracujá", fr:"Margarita au Fruit de la Passion" },
    desc:{ es:"Tequila, maracuyá, triple sec y limón.", en:"Tequila, passion fruit, triple sec and lime.", pt:"Tequila, maracujá, triple sec e limão.", fr:"Tequila, fruit de la passion, triple sec et citron vert." },
    precio:40000, img:"bar-margarita-maracuya-v2", img2:"bar-margarita-maracuya-x", tags:[] },
  { id:"kc5", cat:"bar", sub:"cocteles",
    nombre:{ es:"Daiquiri", en:"Daiquiri", pt:"Daiquiri", fr:"Daiquiri" },
    desc:{ es:"Ron blanco, jugo de limón y azúcar.", en:"White rum, lime juice and sugar.", pt:"Rum branco, suco de limão e açúcar.", fr:"Rhum blanc, jus de citron vert et sucre." },
    precio:40000, img:"bar-daiquiri-v2", img2:"bar-daiquiri-x", tags:[] },
  { id:"kc6", cat:"bar", sub:"cocteles",
    nombre:{ es:"Caipiriña", en:"Caipirinha", pt:"Caipirinha", fr:"Caipirinha" },
    desc:{ es:"Cachaza, lima fresca y azúcar.", en:"Cachaça, fresh lime and sugar.", pt:"Cachaça, limão fresco e açúcar.", fr:"Cachaça, citron vert frais et sucre." },
    precio:40000, img:"bar-caipirina-v2", img2:"bar-caipirina-x", tags:[] },
  { id:"kc7", cat:"bar", sub:"cocteles",
    nombre:{ es:"Cuba Libre", en:"Cuba Libre", pt:"Cuba Libre", fr:"Cuba Libre" },
    desc:{ es:"Ron, gaseosa de cola y lima.", en:"Rum, cola and lime.", pt:"Rum, refrigerante de cola e limão.", fr:"Rhum, soda au cola et citron vert." },
    precio:40000, img:"bar-cuba-libre-v2", img2:"bar-cuba-libre-x", tags:[] },
  { id:"kc8", cat:"bar", sub:"cocteles",
    nombre:{ es:"Gin Tonic", en:"Gin & Tonic", pt:"Gin Tônica", fr:"Gin Tonic" },
    desc:{ es:"Ginebra, agua tónica y toque de cítricos.", en:"Gin, tonic water and a citrus twist.", pt:"Gin, água tônica e toque cítrico.", fr:"Gin, eau tonique et zeste d'agrumes." },
    precio:40000, img:"bar-gin-tonic-v2", img2:"bar-gin-tonic-x", tags:[] },
  { id:"kc9", cat:"bar", sub:"cocteles",
    nombre:{ es:"Aperol Spritz", en:"Aperol Spritz", pt:"Aperol Spritz", fr:"Aperol Spritz" },
    desc:{ es:"Aperol, vino espumante y soda.", en:"Aperol, sparkling wine and soda.", pt:"Aperol, vinho espumante e soda.", fr:"Aperol, vin mousseux et soda." },
    precio:40000, img:"bar-aperol-v2", img2:"bar-aperol-x", tags:[] },

  // ---- COCTELERÍA PREMIUM / PREMIUM COCKTAILS / COQUETELARIA PREMIUM / COCKTAILS PREMIUM ----
  { id:"kp1", cat:"bar", sub:"premium",
    nombre:{ es:"Negroni", en:"Negroni", pt:"Negroni", fr:"Negroni" },
    desc:{ es:"Ginebra, Campari y vermut rojo.", en:"Gin, Campari and sweet vermouth.", pt:"Gin, Campari e vermute tinto.", fr:"Gin, Campari et vermouth rouge." },
    precio:45000, img:"bar-negroni-v2", img2:"bar-negroni-x", tags:[], badge:"bartender" },
  { id:"kp2", cat:"bar", sub:"premium",
    nombre:{ es:"Martini", en:"Martini", pt:"Martini", fr:"Martini" },
    desc:{ es:"Ginebra o vodka con vermut seco.", en:"Gin or vodka with dry vermouth.", pt:"Gin ou vodka com vermute seco.", fr:"Gin ou vodka avec vermouth sec." },
    precio:45000, img:"bar-martini-v2", img2:"bar-martini-x", tags:[] },
  { id:"kp3", cat:"bar", sub:"premium",
    nombre:{ es:"Old Fashion", en:"Old Fashioned", pt:"Old Fashioned", fr:"Old Fashioned" },
    desc:{ es:"Whisky, azúcar y amargo de angostura.", en:"Whisky, sugar and Angostura bitters.", pt:"Whisky, açúcar e amargo de angostura.", fr:"Whisky, sucre et bitter Angostura." },
    precio:45000, img:"bar-old-fashion-v2", img2:"bar-old-fashion-x", tags:[] },
  { id:"kp4", cat:"bar", sub:"premium",
    nombre:{ es:"French 75", en:"French 75", pt:"French 75", fr:"French 75" },
    desc:{ es:"Ginebra, limón, azúcar y vino espumante.", en:"Gin, lemon, sugar and sparkling wine.", pt:"Gin, limão, açúcar e vinho espumante.", fr:"Gin, citron, sucre et vin mousseux." },
    precio:45000, img:"bar-french-75-v2", img2:"bar-french-75-x", tags:[] },
  { id:"kp5", cat:"bar", sub:"premium",
    nombre:{ es:"Boulevardier", en:"Boulevardier", pt:"Boulevardier", fr:"Boulevardier" },
    desc:{ es:"Bourbon, Campari y vermut rojo.", en:"Bourbon, Campari and sweet vermouth.", pt:"Bourbon, Campari e vermute tinto.", fr:"Bourbon, Campari et vermouth rouge." },
    precio:45000, img:"bar-boulevardier-v2", img2:"bar-boulevardier-x", tags:[], badge:"bartender" },

  // ---- VINO & SANGRÍA / WINE & SANGRIA / VINHO & SANGRIA / VIN & SANGRIA ----
  { id:"v1", cat:"bar", sub:"vino",
    nombre:{ es:"Vino Rosadela (Tinto · Rosé · Blanco)", en:"Rosadela Wine (Red · Rosé · White)", pt:"Vinho Rosadela (Tinto · Rosé · Branco)", fr:"Vin Rosadela (Rouge · Rosé · Blanc)" },
    desc:{ es:"Copa individual o botella completa.", en:"Single glass or full bottle.", pt:"Taça individual ou garrafa completa.", fr:"Verre individuel ou bouteille entière." },
    precio:25000, precioBotella:100000, img:"bar-vino-copa", tags:[] },
  { id:"v2", cat:"bar", sub:"vino",
    nombre:{ es:"Sangría (Jarra)", en:"Sangria (Pitcher)", pt:"Sangria (Jarra)", fr:"Sangria (Pichet)" },
    desc:{ es:"Sangría tinta o blanca con fruta fresca.", en:"Red or white house sangria with fresh fruit.", pt:"Sangria tinta ou branca com frutas frescas.", fr:"Sangria rouge ou blanche aux fruits frais." },
    precio:100000, img:"bar-sangria", tags:[] },
  { id:"v7", cat:"bar", sub:"vino",
    nombre:{ es:"Vino Espumante Frizzantino", en:"Frizzantino Sparkling Wine", pt:"Vinho Espumante Frizzantino", fr:"Vin Mousseux Frizzantino" },
    desc:{ es:"Copa individual o botella completa.", en:"Single glass or full bottle.", pt:"Taça individual ou garrafa completa.", fr:"Verre individuel ou bouteille entière." },
    precio:25000, precioBotella:100000, img:"bar-vino-frizzantino", tags:[], badge:"nuevo" },
  { id:"v3", cat:"bar", sub:"vino",
    nombre:{ es:"Finca Las Moras Chardonnay", en:"Finca Las Moras Chardonnay", pt:"Finca Las Moras Chardonnay", fr:"Finca Las Moras Chardonnay" },
    desc:{ es:"Vino blanco argentino de San Juan, fresco y aromático con notas de fruta madura.", en:"Argentine white wine from San Juan, crisp and aromatic with ripe fruit notes.", pt:"Vinho branco argentino de San Juan, fresco e aromático com notas de fruta madura.", fr:"Vin blanc argentin de San Juan, frais et aromatique aux notes de fruits mûrs." },
    precio:95000, img:"bar-las-moras-chardonnay", tags:[] },
  { id:"v4", cat:"bar", sub:"vino",
    nombre:{ es:"Finca Las Moras Cabernet Sauvignon", en:"Finca Las Moras Cabernet Sauvignon", pt:"Finca Las Moras Cabernet Sauvignon", fr:"Finca Las Moras Cabernet Sauvignon" },
    desc:{ es:"Vino tinto argentino de San Juan, cuerpo intenso con notas a frutos rojos y especias.", en:"Argentine red wine from San Juan, full-bodied with red fruit and spice notes.", pt:"Vinho tinto argentino de San Juan, corpo intenso com notas de frutas vermelhas e especiarias.", fr:"Vin rouge argentin de San Juan, corsé aux notes de fruits rouges et d'épices." },
    precio:95000, img:"bar-las-moras-cabernet", tags:[] },
  { id:"v5", cat:"bar", sub:"vino",
    nombre:{ es:"Rosaleda Cabernet Sauvignon", en:"Rosaleda Cabernet Sauvignon", pt:"Rosaleda Cabernet Sauvignon", fr:"Rosaleda Cabernet Sauvignon" },
    desc:{ es:"Vino tinto chileno suave y frutal, fácil de disfrutar en cualquier momento.", en:"Smooth, fruit-forward Chilean red wine, easy to enjoy any time.", pt:"Vinho tinto chileno suave e frutado, fácil de apreciar a qualquer momento.", fr:"Vin rouge chilien souple et fruité, facile à apprécier à tout moment." },
    precio:70000, img:"bar-rosaleda-cabernet", tags:[] },
  { id:"v6", cat:"bar", sub:"vino",
    nombre:{ es:"Rosaleda Sauvignon Blanc", en:"Rosaleda Sauvignon Blanc", pt:"Rosaleda Sauvignon Blanc", fr:"Rosaleda Sauvignon Blanc" },
    desc:{ es:"Vino blanco chileno fresco y ligero, con notas cítricas y herbales.", en:"Fresh, light Chilean white wine with citrus and herbal notes.", pt:"Vinho branco chileno fresco e leve, com notas cítricas e de ervas.", fr:"Vin blanc chilien frais et léger, aux notes d'agrumes et d'herbes." },
    precio:70000, img:"bar-rosaleda-sauvignon-blanc", tags:[] },

  // ---- CERVEZA / BEER / CERVEJA / BIÈRE ----
  { id:"z1", cat:"bar", sub:"cerveza",
    nombre:{ es:"Águila Original", en:"Águila Original", pt:"Águila Original", fr:"Águila Original" },
    desc:{ es:"La cerveza más querida de Colombia, creada en Barranquilla desde 1913.", en:"Colombia's most beloved beer, brewed in Barranquilla since 1913.", pt:"A cerveja mais querida da Colômbia, criada em Barranquilla desde 1913.", fr:"La bière la plus appréciée de Colombie, brassée à Barranquilla depuis 1913." },
    precio:13000, img:"bar-aguila-original", tags:[] },
  { id:"z2", cat:"bar", sub:"cerveza",
    nombre:{ es:"Águila Light", en:"Águila Light", pt:"Águila Light", fr:"Águila Light" },
    desc:{ es:"La versión ligera de la clásica Águila, mismo sabor con menos calorías.", en:"The light version of the classic Águila — same great taste, fewer calories.", pt:"A versão leve da clássica Águila, o mesmo sabor com menos calorias.", fr:"La version légère de la classique Águila, même goût avec moins de calories." },
    precio:13000, img:"bar-aguila-light", tags:[] },
  { id:"z10", cat:"bar", sub:"cerveza",
    nombre:{ es:"Kola & Pola", en:"Kola & Pola", pt:"Kola & Pola", fr:"Kola & Pola" },
    desc:{ es:"Mezcla refrescante de cerveza nacional con Kola Román.", en:"Refreshing blend of domestic lager with Kola Román soda.", pt:"Mistura refrescante de cerveja nacional com Kola Román.", fr:"Mélange rafraîchissant de bière nationale et de soda Kola Román." },
    precio:13000, img:"bar-kola-pola", tags:[], badge:"nuevo" },
  { id:"z3", cat:"bar", sub:"cerveza",
    nombre:{ es:"Club Colombia", en:"Club Colombia", pt:"Club Colombia", fr:"Club Colombia" },
    desc:{ es:"Lager premium colombiana: Dorada, Roja o Negra. Maestría cervecera desde 1928.", en:"Colombia's premium lager: Golden, Red or Black. Master-brewed since 1928.", pt:"Lager premium colombiana: Dourada, Vermelha ou Preta. Maestria cervejeira desde 1928.", fr:"Lager premium colombienne : Dorada, Roja ou Negra. Maîtrise brassicole depuis 1928." },
    precio:15000, img:"bar-club-colombia-dorada", tags:[] },
  { id:"z4", cat:"bar", sub:"cerveza",
    nombre:{ es:"Corona", en:"Corona", pt:"Corona", fr:"Corona" },
    desc:{ es:"Cerveza mexicana ligera y refrescante, ideal con una rodaja de limón.", en:"Light, refreshing Mexican beer, best enjoyed with a lime wedge.", pt:"Cerveja mexicana leve e refrescante, ideal com uma rodela de limão.", fr:"Bière mexicaine légère et rafraîchissante, idéale avec une rondelle de citron vert." },
    precio:17000, img:"bar-corona", tags:[] },
  { id:"z5", cat:"bar", sub:"cerveza",
    nombre:{ es:"Stella Artois", en:"Stella Artois", pt:"Stella Artois", fr:"Stella Artois" },
    desc:{ es:"Lager belga premium, elaborada bajo una tradición cervecera que se remonta a 1366.", en:"Premium Belgian lager, brewed under a tradition dating back to 1366.", pt:"Lager belga premium, elaborada sob uma tradição cervejeira que remonta a 1366.", fr:"Lager belge premium, brassée selon une tradition remontant à 1366." },
    precio:17000, img:"bar-stella-artois", tags:[] },
  { id:"z6", cat:"bar", sub:"cerveza",
    nombre:{ es:"Cerveza Modelo Especial", en:"Modelo Especial", pt:"Cerveja Modelo Especial", fr:"Bière Modelo Especial" },
    desc:{ es:"Lager mexicana de cuerpo medio, refrescante desde 1925.", en:"Medium-bodied Mexican lager, refreshing since 1925.", pt:"Lager mexicana de corpo médio, refrescante desde 1925.", fr:"Lager mexicaine de corps moyen, rafraîchissante depuis 1925." },
    precio:30000, img:"bar-modelo-especial", tags:[] },
  { id:"z7", cat:"bar", sub:"cerveza",
    nombre:{ es:"Smirnoff Ice Manzana Verde", en:"Smirnoff Ice Green Apple", pt:"Smirnoff Ice Maçã Verde", fr:"Smirnoff Ice Pomme Verte" },
    desc:{ es:"Mezcla lista para tomar de vodka Smirnoff con un toque burbujeante de manzana verde.", en:"Ready-to-drink Smirnoff vodka mix with a bubbly green apple twist.", pt:"Mistura pronta para beber de vodka Smirnoff com um toque borbulhante de maçã verde.", fr:"Mélange prêt à boire à base de vodka Smirnoff avec une touche pétillante de pomme verte." },
    precio:19000, img:"bar-smirnoff-ice-manzana", tags:[] },
  { id:"z9", cat:"bar", sub:"cerveza",
    nombre:{ es:"Michelada Colombiana", en:"Colombian Michelada", pt:"Michelada Colombiana", fr:"Michelada Colombienne" },
    desc:{ es:"Borde de sal y limón fresco.", en:"Salt-rimmed with fresh lime.", pt:"Borda de sal com limão fresco.", fr:"Bord de sel et citron vert frais." },
    precio:18000, img:"bar-michelada", tags:[] },

  // ---- LICORES / SPIRITS / DESTILADOS / SPIRITUEUX ----
  { id:"l1", cat:"bar", sub:"licores",
    nombre:{ es:"Ron Viejo de Caldas Tradicional", en:"Viejo de Caldas Rum (Traditional)", pt:"Ron Viejo de Caldas Tradicional", fr:"Rhum Viejo de Caldas Tradicional" },
    desc:{ es:"El ron colombiano #1 en ventas del país, añejado 3 años, suave y de sabor tradicional.", en:"Colombia's #1 selling rum, aged 3 years for a smooth, traditional flavor.", pt:"O rum colombiano mais vendido do país, envelhecido 3 anos, suave e de sabor tradicional.", fr:"Le rhum colombien n°1 des ventes du pays, vieilli 3 ans, doux et de saveur traditionnelle." },
    precio:22000, precioBotella:220000, img:"bar-ron-viejo-caldas", tags:[] },
  { id:"l2", cat:"bar", sub:"licores",
    nombre:{ es:"Buchanan's 12 Años", en:"Buchanan's 12 Years", pt:"Buchanan's 12 Anos", fr:"Buchanan's 12 Ans" },
    desc:{ es:"Whisky escocés mezclado, añejado 12 años, elaborado con pasión desde 1884.", en:"Blended Scotch whisky, aged 12 years, crafted with passion since 1884.", pt:"Whisky escocês misturado, envelhecido 12 anos, elaborado com paixão desde 1884.", fr:"Whisky écossais assemblé, vieilli 12 ans, élaboré avec passion depuis 1884." },
    precio:30000, precioBotella:300000, img:"bar-buchanans-12", tags:[] },
  { id:"l3", cat:"bar", sub:"licores",
    nombre:{ es:"Old Parr 12 Años", en:"Old Parr 12 Years", pt:"Old Parr 12 Anos", fr:"Old Parr 12 Ans" },
    desc:{ es:"Whisky escocés mezclado añejado 12 años, homenaje al legendario Thomas Parr desde 1871.", en:"Blended Scotch whisky aged 12 years, a tribute to the legendary Thomas Parr since 1871.", pt:"Whisky escocês misturado envelhecido 12 anos, homenagem ao lendário Thomas Parr desde 1871.", fr:"Whisky écossais assemblé vieilli 12 ans, hommage au légendaire Thomas Parr depuis 1871." },
    precio:28000, precioBotella:280000, img:"bar-old-parr-12", tags:[] },
  { id:"l4", cat:"bar", sub:"licores",
    nombre:{ es:"Johnnie Walker Black", en:"Johnnie Walker Black", pt:"Johnnie Walker Black", fr:"Johnnie Walker Black" },
    desc:{ es:"Whisky escocés mezclado añejado 12 años, ícono mundial de la coctelería.", en:"Blended Scotch whisky aged 12 years, a world icon of fine whisky.", pt:"Whisky escocês misturado envelhecido 12 anos, ícone mundial da coquetelaria.", fr:"Whisky écossais assemblé vieilli 12 ans, icône mondiale de la mixologie." },
    precio:28000, precioBotella:280000, img:"bar-johnnie-walker-black", tags:[] },
  { id:"l5", cat:"bar", sub:"licores",
    nombre:{ es:"Buchanan's Master", en:"Buchanan's Master", pt:"Buchanan's Master", fr:"Buchanan's Master" },
    desc:{ es:"Whisky escocés premium, mezcla superior con notas dulces y amaderadas.", en:"Premium blended Scotch whisky with sweet, woody notes.", pt:"Whisky escocês premium, mistura superior com notas doces e amadeiradas.", fr:"Whisky écossais premium, assemblage supérieur aux notes douces et boisées." },
    precio:35000, precioBotella:350000, img:"bar-buchanans-master", tags:[] },
  { id:"l8", cat:"bar", sub:"licores",
    nombre:{ es:"Bourbon Bulleit", en:"Bulleit Bourbon", pt:"Bourbon Bulleit", fr:"Bourbon Bulleit" },
    desc:{ es:"Bourbon estadounidense de alto contenido de centeno, con carácter especiado y final largo.", en:"High-rye American bourbon with a bold, spicy character and long finish.", pt:"Bourbon americano com alto teor de centeio, caráter picante e final longo.", fr:"Bourbon américain riche en seigle, au caractère épicé et à la longue finale." },
    precio:35000, precioBotella:350000, img:"bar-black-label", tags:[], badge:"nuevo" },
  { id:"l6", cat:"bar", sub:"licores",
    nombre:{ es:"Tanqueray", en:"Tanqueray Gin", pt:"Tanqueray", fr:"Tanqueray" },
    desc:{ es:"Gin inglés London Dry, receta de cuatro botánicos perfectamente balanceados desde 1830.", en:"English London Dry gin, a signature recipe of four perfectly balanced botanicals since 1830.", pt:"Gin inglês London Dry, receita de quatro botânicos perfeitamente equilibrados desde 1830.", fr:"Gin anglais London Dry, recette de quatre botaniques parfaitement équilibrés depuis 1830." },
    precio:28000, precioBotella:280000, img:"bar-tanqueray", tags:[] },
  { id:"l9", cat:"bar", sub:"licores",
    nombre:{ es:"Smirnoff Vodka", en:"Smirnoff Vodka", pt:"Smirnoff Vodka", fr:"Vodka Smirnoff" },
    desc:{ es:"Vodka triple destilado y filtrado diez veces, suave y versátil para coctelería.", en:"Triple-distilled, ten-times-filtered vodka — smooth and versatile for cocktails.", pt:"Vodka triplo destilada e filtrada dez vezes, suave e versátil para coquetelaria.", fr:"Vodka triple distillée et filtrée dix fois, douce et polyvalente pour la mixologie." },
    precio:25000, precioBotella:250000, img:"bar-smirnoff-ice", tags:[], badge:"nuevo" },
  { id:"l7", cat:"bar", sub:"licores",
    nombre:{ es:"Aguardiente Amarillo", en:"Aguardiente Amarillo", pt:"Aguardiente Amarillo", fr:"Aguardiente Amarillo" },
    desc:{ es:"Aguardiente colombiano sin azúcar, destilado de caña, pionero de los amarillos desde 1885.", en:"Sugar-free Colombian aguardiente, cane-distilled — the pioneer of Colombia's 'yellow' aguardientes since 1885.", pt:"Aguardente colombiana sem açúcar, destilada de cana-de-açúcar, pioneira dos amarelos desde 1885.", fr:"Aguardiente colombien sans sucre, distillé de canne à sucre, pionnier des amarillos depuis 1885." },
    precio:20000, precioBotella:200000, img:"bar-aguardiente-amarillo", tags:[] },
];

const CATEGORIES = [
  // ---- COMIDAS ----
  { id:"desayuno", nombre:{ es:"Desayuno", en:"Breakfast", pt:"Café da Manhã", fr:"Petit-Déjeuner" } },
  { id:"aperitivos", nombre:{ es:"Aperitivos", en:"Starters", pt:"Aperitivos", fr:"Entrées" } },
  { id:"platos", nombre:{ es:"Platos Principales", en:"Main Dishes", pt:"Pratos Principais", fr:"Plats Principaux" } },
  { id:"carnes", nombre:{ es:"Carnes y Mariscos", en:"Meats & Seafood", pt:"Carnes e Frutos do Mar", fr:"Viandes et Fruits de Mer" } },
  { id:"sides", nombre:{ es:"Acompañamientos", en:"Sides", pt:"Acompanhamentos", fr:"Accompagnements" } },
  // ---- BEBIDAS ----
  { id:"cafe", nombre:{ es:"Café", en:"Coffee", pt:"Café", fr:"Café" } },
  { id:"bebidas", nombre:{ es:"Bebidas sin Alcohol", en:"Non-Alcoholic Drinks", pt:"Bebidas sem Álcool", fr:"Boissons sans Alcool" } },
  // ---- ALCOHOL ----
  { id:"bar", nombre:{ es:"Bar & Coctelería", en:"Bar & Cocktails", pt:"Bar & Coquetelaria", fr:"Bar & Cocktails" } },
];

// Subgrupos dentro de la categoría "bar"
const BAR_SUBS = {
  cocteles: { es:"Cócteles", en:"Cocktails", pt:"Coquetéis", fr:"Cocktails" },
  premium: { es:"Coctelería Premium", en:"Premium Cocktails", pt:"Coquetelaria Premium", fr:"Cocktails Premium" },
  vino: { es:"Vino & Sangría", en:"Wine & Sangria", pt:"Vinho & Sangria", fr:"Vin & Sangria" },
  cerveza: { es:"Cerveza", en:"Beer", pt:"Cerveja", fr:"Bière" },
  licores: { es:"Licores", en:"Spirits", pt:"Destilados", fr:"Spiritueux" },
};
